services:
  - type: web
    name: mcp-neo4j-cypher
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USERNAME
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: NEO4J_DATABASE
        value: neo4j
